# Generated by Django 2.0.8 on 2018-09-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorinfo',
            name='days_since_created',
        ),
    ]
