# Generated by Django 2.1.1 on 2018-09-21 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoraccount',
            name='date_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datecreated', to='signup.DonorInfo'),
        ),
        migrations.AlterField(
            model_name='donorinfo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
