# Generated by Django 2.1.1 on 2018-09-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20180921_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donoraccount',
            name='date_created',
        ),
    ]
