# Generated by Django 2.1.1 on 2018-09-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_donorinfo_payment_recvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorinfo',
            name='date_recvd',
            field=models.DateTimeField(null=True),
        ),
    ]
