# Generated by Django 2.1.1 on 2018-09-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_donorinfo_date_recvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='date_recvd',
            field=models.DateField(null=True),
        ),
    ]
