# Generated by Django 2.0.8 on 2018-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20180923_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorinfo',
            name='amount_recvd',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
