# Generated by Django 2.0.8 on 2018-09-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20180922_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='payment_recvd',
            field=models.NullBooleanField(),
        ),
    ]
